[package]
name = "srml-system"
version = "1.0.0"
authors = [
	"Parity Technologies <admin@parity.io>",
	"Osuke Sudo <osuke.sudo@layerx.co.jp>",
	]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", optional = true, features = ["derive"] }
zprimitives = { package = "zerochain-primitives", path = "../../core/primitives", default-features = false }

[dependencies.parity-codec]
default-features = false
features = ['derive']
version = '3.2'

[dependencies.substrate-primitives]
default_features = false
git = 'https://github.com/osuketh/substrate.git'
branch = "patch-zerochain"

[dependencies.rstd]
default_features = false
git = 'https://github.com/osuketh/substrate.git'
package = 'sr-std'
branch = "patch-zerochain"

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/osuketh/substrate.git'
package = 'sr-io'
branch = "patch-zerochain"

[dependencies.primitives]
default_features = false
git = 'https://github.com/osuketh/substrate.git'
package = 'sr-primitives'
branch = "patch-zerochain"

[dependencies.srml-support]
default_features = false
git = 'https://github.com/osuketh/substrate.git'
branch = "patch-zerochain"

[dependencies.safe-mix]
default-features = false
version = '1.0'

[features]
default = ["std"]
std = [
	"zprimitives/std",
	"serde",
	"safe-mix/std",
	"parity-codec/std",
	"substrate-primitives/std",
	"rstd/std",
	"runtime-io/std",
	"srml-support/std",
	"primitives/std",
]
